# Generated by Django 4.2.24 on 2025-10-08 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_alter_producto_codigo_barras'),
        ('Inventario', '0008_alter_factura_id'),
    ]

    operations = [
    ]
